const AppConst = {
  ANNO_TYPE: {
    TEXT_SPILT: 20017,
    TEXT_DESTRUCTION: 20018,
    MEDICAL_RECORD: 20019,
    PRONOUN_RELEVANCE: 20020,
    MEDICAL_TEXT: 20021,
    LUNG_NODULE: 20022,
    ALIGNMENT: 20023,
    OBJECT_DETECTION: 20024,
    PRONOUN_RELEVANCE_MIRROR: 20025,
    AUDIO_TEXT: 20026,
    MOBILE_E2E_TEXT: 20027,
    MULTIPLE_CATEGORY: 20028,
    OBJECT_DETECTION_ATTR: 20029,
    LINE_SEGMENT: 20030,
    MOVING_LINE: 20031,
    OPOD: 20032,
    AUDIO_RECORD: 20033,
  },
  SUBMIT_KEY_CODE: {
    20023: 'Space',
    20024: 'Space',
    20028: 'Space',
    20029: 'Space',
    20030: 'Space',
    20031: 'Space',
    20032: 'Space',
  },
  ANNOTYPES_REVISE_NEEDED: [
    20017,
    20018,
    20019,
    20020,
    20021,
    20022,
    20023,
    20024,
    20025,
    20026,
    20027,
    20028,
    20029,
    20030,
    20031,
    20032,
    20033,
  ],
  DEPLOY_MODE: {
    EXTERNAL: 'external',
    INTERNAL: 'internal',
    COMBINED: 'combined',
  },
  KAKAPO_ERROR_CODE: {
    NOT_AUTHORIZED: 3,
  },
  KAKAPO_ERROR: {
    20000: '没有操作权限',
    20001: '邀请码不可用',
    20002: '新密码不能与旧密码一样',
    20003: '该用户名已存在',
    20004: '请求频率过快',
    20005: '用户不存在',
    20006: '权限检查失败',
    20007: '密码错误',
    20008: '登录失败',
  },
  MOBILE_E2E_TEXT_COLORS: [
    '#ff4d4f',
    '#ffc53d',
    '#73d13d',
    '#597ef7',
    '#d9d9d9',
    '#ff7a45',
    '#ffec3d',
    '#36cfc9',
    '#9254de',
    '#ffa940',
    '#bae637',
    '#40a9ff',
    '#f759ab',
  ],
  MOBILE_E2E_ATTR_TYPES: {
    ATTR_GROUP: 'ATTR_GROUP',
    CONCEPT: 'CONCEPT',
    IS_INT: 'IS_INT',
  },
  MOBILE_E2E_TEXT_LABEL_LIST: {
    CUSTOM_SERVICE: '客服的话',
    CALL_REASON: '来电原因',
    DIFFICULT_SENTENCE: '困难语句',
  },
  ANNO_NAME: {
    20017: '文章拆分',
    20018: '文章解构',
    20019: '病种标注',
    20020: '代词关联',
    20021: '文本结构化',
    20022: '肺结节标注',
    20023: 'Alignment标注',
    20024: '图像Detection',
    20025: '代词关联-合并',
    20026: '语音识别',
  },
  TASK_STATUS: {
    '0': {
      id: 0,
      text: '未开始',
      action: [
        {
          id: 1,
          name: 'start',
          text: '开始',
          icon: 'caret-right',
        },
        {
          id: 4,
          name: 'delete',
          text: '删除',
          icon: 'delete',
        },
      ],
    },
    '1': {
      id: 1,
      text: '已开始',
      action: [
        {
          id: 2,
          name: 'pause',
          text: '暂停',
          icon: 'pause',
        },
        {
          id: 3,
          name: 'check',
          text: '结束',
          icon: 'poweroff',
        },
        {
          id: 7,
          name: 'skip',
          text: '查看反馈问题',
        },
      ],
    },
    '2': {
      id: 2,
      text: '已暂停',
      action: [
        {
          id: 1,
          name: 'continue',
          text: '继续',
          icon: 'caret-right',
        },
        {
          id: 3,
          name: 'check',
          text: '关闭',
          icon: 'poweroff',
        },
        {
          id: 7,
          name: 'skip',
          text: '查看反馈问题',
        },
      ],
    },
    '3': {
      id: 3,
      text: '待验收',
      action: [
        {
          id: 4,
          name: 'checked',
          text: '确认验收',
        },
        {
          id: 7,
          name: 'skip',
          text: '查看反馈问题',
        },
        {
          id: 1,
          name: 'restart',
          text: '重启',
          icon: 'reload',
        },
      ],
    },
    '4': {
      id: 4,
      text: '已验收',
      action: [
        {
          id: 5,
          name: 'close',
          text: '关闭任务',
        },
        {
          id: 7,
          name: 'skip',
          text: '查看反馈问题',
        },
      ],
    },
    '5': {
      id: 5,
      text: '已关闭',
      action: [
        {
          id: 4,
          name: 'open',
          text: '打开任务',
        },
      ],
    },
    '6': {
      id: 6,
      text: '已完成',
    },
  },
  DISPLAY_STATUS: {
    OVERTIME: '已超时',
    PAUSED: '暂停中',
    PROCESSING: '进行中',
  },
  TASK_TYPE: {
    '0': '标注任务',
    '1': '训练任务',
  },
  TASK_TYPE_CONST: {
    ANNO: 0,
    TRAIN: 1,
  },
  SORTER_ORDER: {
    DESC: 'descend',
    ASC: 'ascend',
  },
  REQUIRED_TRAIN: {
    '0': '无',
    '1': 'level 1（recall:60%以上, fa:2以下）',
    '2': 'level 2（recall:80%以上, fa:1以下）',
    '3': 'level 3（recall:90%以上, fa:0.5以下）',
  },
  USER_TASK_STATUS: {
    '0': '未开始',
    '1': '进行中',
    '2': '结果已提交',
    '3': '暂停中',
  },
  USER_ROLE: {
    '0': '普通用户',
    '1': '任务管理员',
    '2': '用户管理员',
    '3': '标注管理员',
  },
  USER_TYPE: {
    ANNOTATOR: 0,
    TASK_ADMIN: 1,
    USER_ADMIN: 2,
    ANNOTATION_ADMIN: 3,
  },
  CONSTANT_TYPE: {
    EXAMINATION_ITEM: 1,
    AUXILIARY_CHECK: 2,
    TEST_ITEM: 3,
    DISEASE_ENTITY: 4,
  },
  TASK_STATUS_CONST: {
    NOT_STARTED: 0,
    STARTED: 1,
    PAUSED: 2,
    CHECKING: 3,
    CHECKED: 4,
    CLOSED: 5,
    FINISHED: 6, // ad-hoc, 表示标注员已完成tab的任务状态集合
  },
  TASK_ACTION: {
    PROGRESS: 'PROGRESS',
    REVIEW: 'REVIEW',
    JOIN: 'JOIN',
    DOWNLOAD: 'DOWNLOAD',
    RELEASE: 'RELEASE',
  },
  USER_TASK_STATUS_CONST: {
    NOT_STARTED: 0,
    START: 1,
    SUBMIT: 2,
    PAUSED: 3,
  },
  ROUTE_ROLE: {
    USER_ADMIN: 'userAdmin',
    TASK_ADMIN: 'taskAdmin',
    ANNOTATOR: 'annotator',
    ANNOTATION_ADMIN: 'annotationAdmin',
  },
  ROUTE_TASK_STATUS: {
    INDEX: 'index',
    NOT_STARTED: 'assign',
    STARTED: 'started',
    PAUSED: 'stopped',
    CHECK: 'check',
    CONTROL: 'control',
    CHECKING: 'checked',
  },
  ANNO_STATUS: {
    NOT_ANNOTATED: 0,
    ANNOTATED: 1,
    SKIPPED: 2,
    SUBMITED: 3,
    TEMPORARY: 4,
    RELEASABLE: 5,
    INVALID: -1,
  },
  MODE: {
    ANNO: 'anno',
    REVIEW: 'user_review',
    SKIP: 'skip',
  },
  USER_STATUS: {
    INITIAL: 0,
    DELETED: 1,
    VALIDATED: 2,
  },
  PALLET: [
    '#b71c1c',
    '#0d47a1',
    '#33691e',
    '#bf360c',
    '#d32f2f',
    '#1976d2',
    '#689f38',
    '#e64a19',
    '#f44336',
    '#2196f3',
    '#8bc34a',
    '#ff5722',
    '#e57373',
    '#64b5f6',
    '#aed581',
    '#ff8a65',
    '#ffcdd2',
    '#bbdefb',
    '#dcedc8',
    '#ffccbc',
    '#880e4f',
    '#01579b',
    '#827717',
    '#3e2723',
    '#c2185b',
    '#0288d1',
    '#afb42b',
    '#5d4037',
    '#e91e63',
    '#03a9f4',
    '#cddc39',
    '#795548',
    '#f06292',
    '#4fc3f7',
    '#dce775',
    '#a1887f',
    '#f8bbd0',
    '#b3e5fc',
    '#f0f4c3',
    '#d7ccc8',
    '#4a148c',
    '#006064',
    '#f57f17',
    '#263238',
    '#7b1fa2',
    '#0097a7',
    '#fbc02d',
    '#455a64',
    '#9c27b0',
    '#00bcd4',
    '#ffeb3b',
    '#607d8b',
    '#ba68c8',
    '#4dd0e1',
    '#fff176',
    '#90a4ae',
    '#e1bee7',
    '#b2ebf2',
    '#fff9c4',
    '#cfd8dc',
    '#311b92',
    '#004d40',
    '#ff6f00',
    '#512da8',
    '#00796b',
    '#ffa000',
    '#673ab7',
    '#009688',
    '#ffc107',
    '#9575cd',
    '#4db6ac',
    '#ffd54f',
    '#d1c4e9',
    '#b2dfdb',
    '#ffecb3',
    '#1a237e',
    '#194D33',
    '#e65100',
    '#303f9f',
    '#388e3c',
    '#f57c00',
    '#3f51b5',
    '#4caf50',
    '#ff9800',
    '#7986cb',
    '#81c784',
    '#ffb74d',
    '#c5cae9',
    '#c8e6c9',
    '#ffe0b2',
  ],
  USER_TYPE_CONST: {
    0: 'ANNOTATOR',
    1: 'TASK_ADMIN',
    2: 'USER_ADMIN',
    3: 'ANNOTATION_ADMIN',
  },
  MENU_ITEMS: {
    USER_ADMIN: [
      {
        URL: 'index',
        ICON: 'icon-user',
        NAME: '用户',
      },
      {
        URL: 'group',
        ICON: 'icon-Grouping',
        NAME: '人员管理',
      },
    ],
    TASK_ADMIN: [
      {
        URL: 'dashboard',
        ICON: 'icon-file_time',
        NAME: '仪表盘',
      },
      {
        URL: 'assign',
        ICON: 'icon-tubiao',
        NAME: '发布',
      },
      {
        URL: 'control',
        ICON: 'icon-kongzhi',
        NAME: '控制',
      },
      {
        URL: 'check',
        ICON: 'icon-yanshou',
        NAME: '验收',
      },
      {
        URL: 'group',
        ICON: 'icon-Grouping',
        NAME: '人员管理',
      },
    ],
    ANNOTATOR: [
      {
        URL: 'index',
        ICON: 'icon-zhuye',
        NAME: '任务市场',
      },
      {
        URL: 'started',
        ICON: 'icon-xiugai',
        NAME: '任务列表',
      },
      {
        URL: 'info',
        ICON: 'icon-user',
        NAME: '个人详情',
      },
    ],
    ANNOTATION_ADMIN: [
      {
        URL: 'dashboard',
        ICON: 'icon-file_time',
        NAME: '仪表盘',
      },
      {
        URL: 'control',
        ICON: 'icon-kongzhi',
        NAME: '控制',
      },
      {
        URL: 'check',
        ICON: 'icon-yanshou',
        NAME: '验收',
      },
      {
        URL: 'group',
        ICON: 'icon-Grouping',
        NAME: '人员管理',
      },
    ],
  },
  DOWNLOAD_TYPE: {
    CSV: 0,
    ANNOTATION_DISTRIBUTION: 1,
  },
};

export default AppConst;
